
kind: ServiceAccount
apiVersion: v1
metadata:
  name: deployment-restart
  namespace: vcid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restart
  namespace: vcid
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["vcid-application"]
    verbs: ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restart
  namespace: vcid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-restart
subjects:
  - kind: ServiceAccount
    name: deployment-restart
    namespace: vcid
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-restart
  namespace: vcid
spec:
  concurrencyPolicy: Forbid
  schedule: '0 * * * *' # Es zählt UTC zeit definiert wann der cronjob laufen soll, konfiguriert auf jede volle stunde 
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: deployment-restart
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl 
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/vcid-application'
